name: Celtics Tracker

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          pip install nba_api pandas requests

      - name: Run tracker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: python discord_celtics_tracker.py
